pages: # the job must be named pages
  image: node:latest
  script:
    - npm ci
    - npm run storybook:build
    - mv public public-vue # GitLab Pages looks in the public folder
    - mv storybook-static public # Rename the storybook-static folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master